#!/usr/bin/env node
'use strict';
const https = require('https');
const CF_ACCOUNT_ID=process.env.CF_ACCOUNT_ID,CF_API_TOKEN=process.env.CF_API_TOKEN,CF_KV_NAMESPACE_ID=process.env.CF_KV_NAMESPACE_ID;
if(!CF_ACCOUNT_ID||!CF_API_TOKEN||!CF_KV_NAMESPACE_ID){console.error('[price-sync] Missing env vars');process.exit(1);}
const NSE_STOCKS=['RELIANCE','TCS','HDFCBANK','BHARTIARTL','ICICIBANK','SBIN','INFY','LICI','HINDUNILVR','ITC','LT','KOTAKBANK','BAJFINANCE','HCLTECH','SUNPHARMA','NTPC','ONGC','ULTRACEMCO','MARUTI','WIPRO','BAJAJFINSV','TITAN','POWERGRID','ADANIENT','COALINDIA','ASIANPAINT','NESTLEIND','INDUSINDBK','AXISBANK','ADANIPORTS','JSWSTEEL','HINDALCO','GRASIM','TECHM','TATAMOTORS','DRREDDY','CIPLA','DIVISLAB','APOLLOHOSP','EICHERMOT','TATACONSUM','SBILIFE','HDFCLIFE','ICICIPRULI','BAJAJ-AUTO','BRITANNIA','HEROMOTOCO','M&M','TATASTEEL','BPCL','ADANIGREEN','ADANITRANS','SIEMENS','ABB','PIDILITIND','HAVELLS','BERGEPAINT','MARICO','GODREJCP','COLPAL','DABUR','EMAMILTD','MUTHOOTFIN','CHOLAFIN','BAJAJHLDNG','BOSCHLTD','TORNTPHARM','AUROPHARMA','LUPIN','BIOCON','DMART','TRENT','IRCTC','INDIGO','JUBLFOOD','MCDOWELL-N','UNITDSPR','SHREECEM','AMBUJACEM','ACCLTD','SAIL','NMDC','NATIONALUM','HINDZINC','VEDL','JINDALSTEL','JSWENERGY','TATAPOWER','RECLTD','PFC','IRFC','RVNL','CONCOR','TIINDIA','VOLTAS','BLUEDART','DELHIVERY','NAUKRI','AFFLE','PERSISTENT','MPHASIS','LTIM','COFORGE','TATAELXSI','KPITTECH','CYIENT','ZENSAR','OFSS','NEWGEN','NETWEB','KAYNES','DIXON','AMBER','HAPPSTMNDS','RATEGAIN','MASTEK','INTELLECT','BANKBARODA','CANARABANK','UNIONBANK','INDIANB','PNB','FEDERALBNK','IDFCFIRSTB','YESBANK','RBLBANK','DCBBANK','UJJIVANSFB','KTKBANK','MANAPPURAM','IIFL','CANFINHOME','AAVAS','REPCO','HOMEFIRST','ANGELONE','MOTILALOFS','SBICARDS','ICICIGI','STARHEALTH','GICRE','NIACL','ZYDUSLIFE','ALKEM','NATCOPHARM','IPCA','AJANTPHARMA','GRANULES','LAURUSLABS','GLAXO','PFIZER','ASTRAZEN','SANOFI','ABBOT','ESCORTS','FORCEMOT','ENDURANCE','EXIDEIND','SUNDRMFAST','TIMKEN','SCHAEFFLER','SKF','CRAFTSMAN','RAMCOCEM','JKCEMENT','DALBHARAT','KNRCON','PNCINFRA','NBCC','NCC','IRCON','RAILTEL','TITAGARH','GPPL','CESC','TORNTPOWER','NLCLINDIA','NHPC','SJVN','GIPCL','ADANIPOWER','RADICO','BALRAMCHIN','TRIVENI','VBL','BIKAJI','VENKEYS','WESTLIFE','DEVYANI','SULA','DLF','LODHA','GODREJPROP','PRESTIGE','BRIGADE','SOBHA','PHOENIXLTD','OBEROIRLTY','SUNTECK','KOLTEPATIL','TATACOMM','HFCL','ROUTE','TEJASNET','DEEPAKNITRITE','AARTI','PIIND','SUMCHEM','FINEORG','GALAXYSURF','TATACHEM','CHAMBALFERT','COROMANDEL','GNFC','NOCIL','BHEL','HAL','BEL','BEML','COCHINSHIP','GRSE','MAZAGON','CUMMINSIND','THERMAX','RAMKRISHNA','RATNAMANI','WELCORP','V2RETAIL','SHOPERSTOP','BATAINDIA','VMART','MANYAVAR','METRO','KALYANKJIL','SENCO','RAJESHEXPO','GMRINFRA','ADANIGAS','NYKAA','ZOMATO','PAYTM','POLICYBZR','HDFCSEC','CRISIL','ICRA','CARERATINGS','UIICL'];
const BSE_STOCKS=['TATASTEELLP','TATAMETALI','BIRLATYRE','BHAGCHEM','ZYDUSWELL','NAVNETEDUL','SUNTV','MFSL'];
const UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36';
function httpsGetRaw(url,extraHeaders){return new Promise((resolve,reject)=>{const req=https.get(url,{headers:{'User-Agent':UA,'Accept':'application/json, text/plain, */*','Accept-Language':'en-US,en;q=0.9','Referer':'https://finance.yahoo.com/',...extraHeaders},timeout:15000},res=>{if((res.statusCode===301||res.statusCode===302)&&res.headers.location){return httpsGetRaw(res.headers.location,extraHeaders).then(resolve).catch(reject);}let body='';res.on('data',d=>body+=d);res.on('end',()=>resolve({status:res.statusCode,body,headers:res.headers}));});req.on('error',reject);req.on('timeout',()=>{req.destroy();reject(new Error('timeout'));});});}
async function httpsGetJSON(url,cookies){const headers=cookies?{'Cookie':cookies}:{};const{status,body}=await httpsGetRaw(url,headers);try{return JSON.parse(body);}catch(e){throw new Error('HTTP '+status+': '+body.slice(0,200));}}
async function getYFSession(){console.log('[price-sync] Fetching YF session...');const cookies=await new Promise((resolve,reject)=>{const req=https.get('https://finance.yahoo.com/',{headers:{'User-Agent':UA,'Accept':'text/html,*/*','Accept-Language':'en-US,en;q=0.9'},timeout:20000},res=>{const cs=(res.headers['set-cookie']||[]).map(c=>c.split(';')[0]).join('; ');res.resume();res.on('end',()=>resolve(cs));});req.on('error',reject);req.on('timeout',()=>{req.destroy();reject(new Error('YF timeout'));});});console.log('[price-sync] Cookies: '+cookies.substring(0,80));const crumb=await new Promise((resolve,reject)=>{const req=https.get('https://query2.finance.yahoo.com/v1/test/getcrumb',{headers:{'User-Agent':UA,'Cookie':cookies,'Referer':'https://finance.yahoo.com/','Accept':'*/*'},timeout:15000},res=>{let body='';res.on('data',d=>body+=d);res.on('end',()=>{const t=body.trim();if(t&&!t.startsWith('<')&&!t.startsWith('{'))resolve(t);else reject(new Error('Bad crumb ('+res.statusCode+'): '+t.slice(0,100)));});});req.on('error',reject);req.on('timeout',()=>{req.destroy();reject(new Error('crumb timeout'));});});console.log('[price-sync] Crumb: '+crumb);return{cookies,crumb};}
async function fetchBatch(symbols,session){const q=encodeURIComponent(symbols.join(','));const fields='regularMarketPrice,regularMarketChangePercent';const crumbQ=session?'&crumb='+encodeURIComponent(session.crumb):'';const cookies=session?session.cookies:null;for(const host of['query1','query2']){const url='https://'+host+'.finance.yahoo.com/v7/finance/quote?symbols='+q+'&fields='+fields+'&formatted=false'+crumbQ;try{const data=await httpsGetJSON(url,cookies);const results=data&&data.quoteResponse&&data.quoteResponse.result;if(Array.isArray(results)&&results.length>0)return results;if(Array.isArray(results))console.warn('[price-sync] '+host+' empty for '+symbols[0]);}catch(e){console.warn('[price-sync] '+host+' failed ('+symbols[0]+'): '+e.message.slice(0,100));}}return[];}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function writeToKV(key,value){const body=JSON.stringify(value);const url=new URL('https://api.cloudflare.com/client/v4/accounts/'+CF_ACCOUNT_ID+'/storage/kv/namespaces/'+CF_KV_NAMESPACE_ID+'/values/'+key);return new Promise((resolve,reject)=>{const options={hostname:url.hostname,path:url.pathname,method:'PUT',headers:{'Authorization':'Bearer '+CF_API_TOKEN,'Content-Type':'application/json','Content-Length':Buffer.byteLength(body)},timeout:20000};const req=https.request(options,res=>{let data='';res.on('data',d=>data+=d);res.on('end',()=>{try{const p=JSON.parse(data);if(p.success)resolve(p);else reject(new Error('KV write failed: '+JSON.stringify(p.errors)));}catch(e){reject(e);}});});req.on('error',reject);req.on('timeout',()=>{req.destroy();reject(new Error('KV timeout'));});req.write(body);req.end();});}
async function main(){const startTs=Date.now();console.log('[price-sync] Starting at '+new Date(startTs).toISOString());let session=null;try{session=await getYFSession();}catch(e){console.warn('[price-sync] No session: '+e.message);}
const nseSyms=[...new Set(NSE_STOCKS)].map(s=>s+'.NS');const bseSyms=[...new Set(BSE_STOCKS)].map(s=>s+'.BO');const allSyms=[...nseSyms,...bseSyms];console.log('[price-sync] Querying '+allSyms.length+' symbols in batches of 50...');const BATCH=50;const prices={};let fetched=0,batches=0;for(let i=0;i<allSyms.length;i+=BATCH){const batch=allSyms.slice(i,i+BATCH);const quotes=await fetchBatch(batch,session);batches++;quotes.forEach(q=>{const sym=q.symbol||'';const isNS=sym.endsWith('.NS'),isBO=sym.endsWith('.BO');if(!isNS&&!isBO)return;const base=sym.replace(/\.(NS|BO)$/,'');const xch=isNS?'NSE':'BSE';const ltp=q.regularMarketPrice||0;const chgP=q.regularMarketChangePercent||0;if(ltp){prices[base+'|'+xch]={ltp,chgP};fetched++;}});if(i+BATCH<allSyms.length)await sleep(300);}const elapsed=Date.now()-startTs;console.log('[price-sync] Fetched '+fetched+' prices across '+batches+' batches in '+elapsed+'ms');if(!fetched){console.warn('[price-sync] No prices - skipping KV write');process.exit(1);}const payload={ts:Date.now(),prices};await writeToKV('priceCache',payload);console.log('[price-sync] Written '+fetched+' prices to KV');}
main().catch(e=>{console.error('[price-sync] Fatal:',e.message);process.exit(1);});
